<?xml version="1.0" encoding="utf-8"?><Database Name="ql_DatDo" Class="dbcsdlDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-6MF64C4\SQLEXPRESS;Initial Catalog=ql_DatDo;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ql_DatDoConnectionString" Provider="System.Data.SqlClient" />
</Database>