#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="db_ql")]
public partial class dbcsdlDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void Insertadmin_AccessGroupUserForm(admin_AccessGroupUserForm instance);
  partial void Updateadmin_AccessGroupUserForm(admin_AccessGroupUserForm instance);
  partial void Deleteadmin_AccessGroupUserForm(admin_AccessGroupUserForm instance);
  partial void Insertadmin_AccessGroupUserModule(admin_AccessGroupUserModule instance);
  partial void Updateadmin_AccessGroupUserModule(admin_AccessGroupUserModule instance);
  partial void Deleteadmin_AccessGroupUserModule(admin_AccessGroupUserModule instance);
  partial void Insertadmin_AccessUserForm(admin_AccessUserForm instance);
  partial void Updateadmin_AccessUserForm(admin_AccessUserForm instance);
  partial void Deleteadmin_AccessUserForm(admin_AccessUserForm instance);
  partial void Insertadmin_Form(admin_Form instance);
  partial void Updateadmin_Form(admin_Form instance);
  partial void Deleteadmin_Form(admin_Form instance);
  partial void Insertadmin_GroupUser(admin_GroupUser instance);
  partial void Updateadmin_GroupUser(admin_GroupUser instance);
  partial void Deleteadmin_GroupUser(admin_GroupUser instance);
  partial void Insertadmin_Module(admin_Module instance);
  partial void Updateadmin_Module(admin_Module instance);
  partial void Deleteadmin_Module(admin_Module instance);
  partial void Insertadmin_User(admin_User instance);
  partial void Updateadmin_User(admin_User instance);
  partial void Deleteadmin_User(admin_User instance);
  partial void Inserttb_Category(tb_Category instance);
  partial void Updatetb_Category(tb_Category instance);
  partial void Deletetb_Category(tb_Category instance);
  partial void Inserttb_Product(tb_Product instance);
  partial void Updatetb_Product(tb_Product instance);
  partial void Deletetb_Product(tb_Product instance);
  partial void Inserttb_slide(tb_slide instance);
  partial void Updatetb_slide(tb_slide instance);
  partial void Deletetb_slide(tb_slide instance);
  partial void Inserttb_User(tb_User instance);
  partial void Updatetb_User(tb_User instance);
  partial void Deletetb_User(tb_User instance);
  partial void Inserttb_Restaurant(tb_Restaurant instance);
  partial void Updatetb_Restaurant(tb_Restaurant instance);
  partial void Deletetb_Restaurant(tb_Restaurant instance);
  partial void Inserttb_Book(tb_Book instance);
  partial void Updatetb_Book(tb_Book instance);
  partial void Deletetb_Book(tb_Book instance);
  partial void Inserttb_OrderDetail(tb_OrderDetail instance);
  partial void Updatetb_OrderDetail(tb_OrderDetail instance);
  partial void Deletetb_OrderDetail(tb_OrderDetail instance);
  partial void Inserttb_Order(tb_Order instance);
  partial void Updatetb_Order(tb_Order instance);
  partial void Deletetb_Order(tb_Order instance);
  #endregion
	
	public dbcsdlDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["db_qlConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public dbcsdlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<admin_AccessGroupUserForm> admin_AccessGroupUserForms
	{
		get
		{
			return this.GetTable<admin_AccessGroupUserForm>();
		}
	}
	
	public System.Data.Linq.Table<admin_AccessGroupUserModule> admin_AccessGroupUserModules
	{
		get
		{
			return this.GetTable<admin_AccessGroupUserModule>();
		}
	}
	
	public System.Data.Linq.Table<admin_AccessUserForm> admin_AccessUserForms
	{
		get
		{
			return this.GetTable<admin_AccessUserForm>();
		}
	}
	
	public System.Data.Linq.Table<admin_Form> admin_Forms
	{
		get
		{
			return this.GetTable<admin_Form>();
		}
	}
	
	public System.Data.Linq.Table<admin_GroupUser> admin_GroupUsers
	{
		get
		{
			return this.GetTable<admin_GroupUser>();
		}
	}
	
	public System.Data.Linq.Table<admin_Module> admin_Modules
	{
		get
		{
			return this.GetTable<admin_Module>();
		}
	}
	
	public System.Data.Linq.Table<admin_User> admin_Users
	{
		get
		{
			return this.GetTable<admin_User>();
		}
	}
	
	public System.Data.Linq.Table<tb_Category> tb_Categories
	{
		get
		{
			return this.GetTable<tb_Category>();
		}
	}
	
	public System.Data.Linq.Table<tb_Product> tb_Products
	{
		get
		{
			return this.GetTable<tb_Product>();
		}
	}
	
	public System.Data.Linq.Table<tb_slide> tb_slides
	{
		get
		{
			return this.GetTable<tb_slide>();
		}
	}
	
	public System.Data.Linq.Table<tb_User> tb_Users
	{
		get
		{
			return this.GetTable<tb_User>();
		}
	}
	
	public System.Data.Linq.Table<tb_Restaurant> tb_Restaurants
	{
		get
		{
			return this.GetTable<tb_Restaurant>();
		}
	}
	
	public System.Data.Linq.Table<tb_Book> tb_Books
	{
		get
		{
			return this.GetTable<tb_Book>();
		}
	}
	
	public System.Data.Linq.Table<tb_OrderDetail> tb_OrderDetails
	{
		get
		{
			return this.GetTable<tb_OrderDetail>();
		}
	}
	
	public System.Data.Linq.Table<tb_Order> tb_Orders
	{
		get
		{
			return this.GetTable<tb_Order>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_AccessGroupUserForm")]
public partial class admin_AccessGroupUserForm : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _guf_id;
	
	private System.Nullable<bool> _guf_active;
	
	private System.Nullable<int> _groupuser_id;
	
	private System.Nullable<int> _form_id;
	
	private EntityRef<admin_Form> _admin_Form;
	
	private EntityRef<admin_GroupUser> _admin_GroupUser;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onguf_idChanging(int value);
    partial void Onguf_idChanged();
    partial void Onguf_activeChanging(System.Nullable<bool> value);
    partial void Onguf_activeChanged();
    partial void Ongroupuser_idChanging(System.Nullable<int> value);
    partial void Ongroupuser_idChanged();
    partial void Onform_idChanging(System.Nullable<int> value);
    partial void Onform_idChanged();
    #endregion
	
	public admin_AccessGroupUserForm()
	{
		this._admin_Form = default(EntityRef<admin_Form>);
		this._admin_GroupUser = default(EntityRef<admin_GroupUser>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guf_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int guf_id
	{
		get
		{
			return this._guf_id;
		}
		set
		{
			if ((this._guf_id != value))
			{
				this.Onguf_idChanging(value);
				this.SendPropertyChanging();
				this._guf_id = value;
				this.SendPropertyChanged("guf_id");
				this.Onguf_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_guf_active", DbType="Bit")]
	public System.Nullable<bool> guf_active
	{
		get
		{
			return this._guf_active;
		}
		set
		{
			if ((this._guf_active != value))
			{
				this.Onguf_activeChanging(value);
				this.SendPropertyChanging();
				this._guf_active = value;
				this.SendPropertyChanged("guf_active");
				this.Onguf_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", DbType="Int")]
	public System.Nullable<int> groupuser_id
	{
		get
		{
			return this._groupuser_id;
		}
		set
		{
			if ((this._groupuser_id != value))
			{
				if (this._admin_GroupUser.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ongroupuser_idChanging(value);
				this.SendPropertyChanging();
				this._groupuser_id = value;
				this.SendPropertyChanged("groupuser_id");
				this.Ongroupuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_id", DbType="Int")]
	public System.Nullable<int> form_id
	{
		get
		{
			return this._form_id;
		}
		set
		{
			if ((this._form_id != value))
			{
				if (this._admin_Form.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Onform_idChanging(value);
				this.SendPropertyChanging();
				this._form_id = value;
				this.SendPropertyChanged("form_id");
				this.Onform_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Form_admin_AccessGroupUserForm", Storage="_admin_Form", ThisKey="form_id", OtherKey="form_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public admin_Form admin_Form
	{
		get
		{
			return this._admin_Form.Entity;
		}
		set
		{
			admin_Form previousValue = this._admin_Form.Entity;
			if (((previousValue != value) 
						|| (this._admin_Form.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._admin_Form.Entity = null;
					previousValue.admin_AccessGroupUserForms.Remove(this);
				}
				this._admin_Form.Entity = value;
				if ((value != null))
				{
					value.admin_AccessGroupUserForms.Add(this);
					this._form_id = value.form_id;
				}
				else
				{
					this._form_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("admin_Form");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_AccessGroupUserForm", Storage="_admin_GroupUser", ThisKey="groupuser_id", OtherKey="groupuser_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public admin_GroupUser admin_GroupUser
	{
		get
		{
			return this._admin_GroupUser.Entity;
		}
		set
		{
			admin_GroupUser previousValue = this._admin_GroupUser.Entity;
			if (((previousValue != value) 
						|| (this._admin_GroupUser.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._admin_GroupUser.Entity = null;
					previousValue.admin_AccessGroupUserForms.Remove(this);
				}
				this._admin_GroupUser.Entity = value;
				if ((value != null))
				{
					value.admin_AccessGroupUserForms.Add(this);
					this._groupuser_id = value.groupuser_id;
				}
				else
				{
					this._groupuser_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("admin_GroupUser");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_AccessGroupUserModule")]
public partial class admin_AccessGroupUserModule : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _gum_id;
	
	private System.Nullable<bool> _gum_active;
	
	private System.Nullable<int> _groupuser_id;
	
	private System.Nullable<int> _module_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongum_idChanging(int value);
    partial void Ongum_idChanged();
    partial void Ongum_activeChanging(System.Nullable<bool> value);
    partial void Ongum_activeChanged();
    partial void Ongroupuser_idChanging(System.Nullable<int> value);
    partial void Ongroupuser_idChanged();
    partial void Onmodule_idChanging(System.Nullable<int> value);
    partial void Onmodule_idChanged();
    #endregion
	
	public admin_AccessGroupUserModule()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gum_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int gum_id
	{
		get
		{
			return this._gum_id;
		}
		set
		{
			if ((this._gum_id != value))
			{
				this.Ongum_idChanging(value);
				this.SendPropertyChanging();
				this._gum_id = value;
				this.SendPropertyChanged("gum_id");
				this.Ongum_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gum_active", DbType="Bit")]
	public System.Nullable<bool> gum_active
	{
		get
		{
			return this._gum_active;
		}
		set
		{
			if ((this._gum_active != value))
			{
				this.Ongum_activeChanging(value);
				this.SendPropertyChanging();
				this._gum_active = value;
				this.SendPropertyChanged("gum_active");
				this.Ongum_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", DbType="Int")]
	public System.Nullable<int> groupuser_id
	{
		get
		{
			return this._groupuser_id;
		}
		set
		{
			if ((this._groupuser_id != value))
			{
				this.Ongroupuser_idChanging(value);
				this.SendPropertyChanging();
				this._groupuser_id = value;
				this.SendPropertyChanged("groupuser_id");
				this.Ongroupuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="Int")]
	public System.Nullable<int> module_id
	{
		get
		{
			return this._module_id;
		}
		set
		{
			if ((this._module_id != value))
			{
				this.Onmodule_idChanging(value);
				this.SendPropertyChanging();
				this._module_id = value;
				this.SendPropertyChanged("module_id");
				this.Onmodule_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_AccessUserForm")]
public partial class admin_AccessUserForm : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _uf_id;
	
	private System.Nullable<bool> _uf_active;
	
	private System.Nullable<int> _username_id;
	
	private System.Nullable<int> _form_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuf_idChanging(int value);
    partial void Onuf_idChanged();
    partial void Onuf_activeChanging(System.Nullable<bool> value);
    partial void Onuf_activeChanged();
    partial void Onusername_idChanging(System.Nullable<int> value);
    partial void Onusername_idChanged();
    partial void Onform_idChanging(System.Nullable<int> value);
    partial void Onform_idChanged();
    #endregion
	
	public admin_AccessUserForm()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int uf_id
	{
		get
		{
			return this._uf_id;
		}
		set
		{
			if ((this._uf_id != value))
			{
				this.Onuf_idChanging(value);
				this.SendPropertyChanging();
				this._uf_id = value;
				this.SendPropertyChanged("uf_id");
				this.Onuf_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_uf_active", DbType="Bit")]
	public System.Nullable<bool> uf_active
	{
		get
		{
			return this._uf_active;
		}
		set
		{
			if ((this._uf_active != value))
			{
				this.Onuf_activeChanging(value);
				this.SendPropertyChanging();
				this._uf_active = value;
				this.SendPropertyChanged("uf_active");
				this.Onuf_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_id", DbType="Int")]
	public System.Nullable<int> username_id
	{
		get
		{
			return this._username_id;
		}
		set
		{
			if ((this._username_id != value))
			{
				this.Onusername_idChanging(value);
				this.SendPropertyChanging();
				this._username_id = value;
				this.SendPropertyChanged("username_id");
				this.Onusername_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_id", DbType="Int")]
	public System.Nullable<int> form_id
	{
		get
		{
			return this._form_id;
		}
		set
		{
			if ((this._form_id != value))
			{
				this.Onform_idChanging(value);
				this.SendPropertyChanging();
				this._form_id = value;
				this.SendPropertyChanged("form_id");
				this.Onform_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_Form")]
public partial class admin_Form : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _form_id;
	
	private System.Nullable<int> _form_position;
	
	private string _form_name;
	
	private string _form_link;
	
	private System.Nullable<bool> _form_active;
	
	private System.Nullable<int> _module_id;
	
	private EntitySet<admin_AccessGroupUserForm> _admin_AccessGroupUserForms;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onform_idChanging(int value);
    partial void Onform_idChanged();
    partial void Onform_positionChanging(System.Nullable<int> value);
    partial void Onform_positionChanged();
    partial void Onform_nameChanging(string value);
    partial void Onform_nameChanged();
    partial void Onform_linkChanging(string value);
    partial void Onform_linkChanged();
    partial void Onform_activeChanging(System.Nullable<bool> value);
    partial void Onform_activeChanged();
    partial void Onmodule_idChanging(System.Nullable<int> value);
    partial void Onmodule_idChanged();
    #endregion
	
	public admin_Form()
	{
		this._admin_AccessGroupUserForms = new EntitySet<admin_AccessGroupUserForm>(new Action<admin_AccessGroupUserForm>(this.attach_admin_AccessGroupUserForms), new Action<admin_AccessGroupUserForm>(this.detach_admin_AccessGroupUserForms));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int form_id
	{
		get
		{
			return this._form_id;
		}
		set
		{
			if ((this._form_id != value))
			{
				this.Onform_idChanging(value);
				this.SendPropertyChanging();
				this._form_id = value;
				this.SendPropertyChanged("form_id");
				this.Onform_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_position", DbType="Int")]
	public System.Nullable<int> form_position
	{
		get
		{
			return this._form_position;
		}
		set
		{
			if ((this._form_position != value))
			{
				this.Onform_positionChanging(value);
				this.SendPropertyChanging();
				this._form_position = value;
				this.SendPropertyChanged("form_position");
				this.Onform_positionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_name", DbType="NVarChar(MAX)")]
	public string form_name
	{
		get
		{
			return this._form_name;
		}
		set
		{
			if ((this._form_name != value))
			{
				this.Onform_nameChanging(value);
				this.SendPropertyChanging();
				this._form_name = value;
				this.SendPropertyChanged("form_name");
				this.Onform_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_link", DbType="NVarChar(MAX)")]
	public string form_link
	{
		get
		{
			return this._form_link;
		}
		set
		{
			if ((this._form_link != value))
			{
				this.Onform_linkChanging(value);
				this.SendPropertyChanging();
				this._form_link = value;
				this.SendPropertyChanged("form_link");
				this.Onform_linkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_form_active", DbType="Bit")]
	public System.Nullable<bool> form_active
	{
		get
		{
			return this._form_active;
		}
		set
		{
			if ((this._form_active != value))
			{
				this.Onform_activeChanging(value);
				this.SendPropertyChanging();
				this._form_active = value;
				this.SendPropertyChanged("form_active");
				this.Onform_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", DbType="Int")]
	public System.Nullable<int> module_id
	{
		get
		{
			return this._module_id;
		}
		set
		{
			if ((this._module_id != value))
			{
				this.Onmodule_idChanging(value);
				this.SendPropertyChanging();
				this._module_id = value;
				this.SendPropertyChanged("module_id");
				this.Onmodule_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_Form_admin_AccessGroupUserForm", Storage="_admin_AccessGroupUserForms", ThisKey="form_id", OtherKey="form_id")]
	public EntitySet<admin_AccessGroupUserForm> admin_AccessGroupUserForms
	{
		get
		{
			return this._admin_AccessGroupUserForms;
		}
		set
		{
			this._admin_AccessGroupUserForms.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_admin_AccessGroupUserForms(admin_AccessGroupUserForm entity)
	{
		this.SendPropertyChanging();
		entity.admin_Form = this;
	}
	
	private void detach_admin_AccessGroupUserForms(admin_AccessGroupUserForm entity)
	{
		this.SendPropertyChanging();
		entity.admin_Form = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_GroupUser")]
public partial class admin_GroupUser : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _groupuser_id;
	
	private string _groupuser_name;
	
	private System.Nullable<bool> _groupuser_active;
	
	private EntitySet<admin_AccessGroupUserForm> _admin_AccessGroupUserForms;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ongroupuser_idChanging(int value);
    partial void Ongroupuser_idChanged();
    partial void Ongroupuser_nameChanging(string value);
    partial void Ongroupuser_nameChanged();
    partial void Ongroupuser_activeChanging(System.Nullable<bool> value);
    partial void Ongroupuser_activeChanged();
    #endregion
	
	public admin_GroupUser()
	{
		this._admin_AccessGroupUserForms = new EntitySet<admin_AccessGroupUserForm>(new Action<admin_AccessGroupUserForm>(this.attach_admin_AccessGroupUserForms), new Action<admin_AccessGroupUserForm>(this.detach_admin_AccessGroupUserForms));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int groupuser_id
	{
		get
		{
			return this._groupuser_id;
		}
		set
		{
			if ((this._groupuser_id != value))
			{
				this.Ongroupuser_idChanging(value);
				this.SendPropertyChanging();
				this._groupuser_id = value;
				this.SendPropertyChanged("groupuser_id");
				this.Ongroupuser_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_name", DbType="NVarChar(MAX)")]
	public string groupuser_name
	{
		get
		{
			return this._groupuser_name;
		}
		set
		{
			if ((this._groupuser_name != value))
			{
				this.Ongroupuser_nameChanging(value);
				this.SendPropertyChanging();
				this._groupuser_name = value;
				this.SendPropertyChanged("groupuser_name");
				this.Ongroupuser_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_active", DbType="Bit")]
	public System.Nullable<bool> groupuser_active
	{
		get
		{
			return this._groupuser_active;
		}
		set
		{
			if ((this._groupuser_active != value))
			{
				this.Ongroupuser_activeChanging(value);
				this.SendPropertyChanging();
				this._groupuser_active = value;
				this.SendPropertyChanged("groupuser_active");
				this.Ongroupuser_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="admin_GroupUser_admin_AccessGroupUserForm", Storage="_admin_AccessGroupUserForms", ThisKey="groupuser_id", OtherKey="groupuser_id")]
	public EntitySet<admin_AccessGroupUserForm> admin_AccessGroupUserForms
	{
		get
		{
			return this._admin_AccessGroupUserForms;
		}
		set
		{
			this._admin_AccessGroupUserForms.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_admin_AccessGroupUserForms(admin_AccessGroupUserForm entity)
	{
		this.SendPropertyChanging();
		entity.admin_GroupUser = this;
	}
	
	private void detach_admin_AccessGroupUserForms(admin_AccessGroupUserForm entity)
	{
		this.SendPropertyChanging();
		entity.admin_GroupUser = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_Module")]
public partial class admin_Module : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _module_id;
	
	private System.Nullable<int> _module_position;
	
	private string _module_name;
	
	private string _module_icon;
	
	private System.Nullable<bool> _module_active;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onmodule_idChanging(int value);
    partial void Onmodule_idChanged();
    partial void Onmodule_positionChanging(System.Nullable<int> value);
    partial void Onmodule_positionChanged();
    partial void Onmodule_nameChanging(string value);
    partial void Onmodule_nameChanged();
    partial void Onmodule_iconChanging(string value);
    partial void Onmodule_iconChanged();
    partial void Onmodule_activeChanging(System.Nullable<bool> value);
    partial void Onmodule_activeChanged();
    #endregion
	
	public admin_Module()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int module_id
	{
		get
		{
			return this._module_id;
		}
		set
		{
			if ((this._module_id != value))
			{
				this.Onmodule_idChanging(value);
				this.SendPropertyChanging();
				this._module_id = value;
				this.SendPropertyChanged("module_id");
				this.Onmodule_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_position", DbType="Int")]
	public System.Nullable<int> module_position
	{
		get
		{
			return this._module_position;
		}
		set
		{
			if ((this._module_position != value))
			{
				this.Onmodule_positionChanging(value);
				this.SendPropertyChanging();
				this._module_position = value;
				this.SendPropertyChanged("module_position");
				this.Onmodule_positionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_name", DbType="NVarChar(MAX)")]
	public string module_name
	{
		get
		{
			return this._module_name;
		}
		set
		{
			if ((this._module_name != value))
			{
				this.Onmodule_nameChanging(value);
				this.SendPropertyChanging();
				this._module_name = value;
				this.SendPropertyChanged("module_name");
				this.Onmodule_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_icon", DbType="NVarChar(MAX)")]
	public string module_icon
	{
		get
		{
			return this._module_icon;
		}
		set
		{
			if ((this._module_icon != value))
			{
				this.Onmodule_iconChanging(value);
				this.SendPropertyChanging();
				this._module_icon = value;
				this.SendPropertyChanged("module_icon");
				this.Onmodule_iconChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_module_active", DbType="Bit")]
	public System.Nullable<bool> module_active
	{
		get
		{
			return this._module_active;
		}
		set
		{
			if ((this._module_active != value))
			{
				this.Onmodule_activeChanging(value);
				this.SendPropertyChanging();
				this._module_active = value;
				this.SendPropertyChanged("module_active");
				this.Onmodule_activeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.admin_User")]
public partial class admin_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _username_id;
	
	private string _username_username;
	
	private string _username_password;
	
	private string _username_fullname;
	
	private System.Nullable<bool> _username_gender;
	
	private string _username_phone;
	
	private string _username_email;
	
	private System.Nullable<bool> _username_active;
	
	private System.Nullable<int> _groupuser_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onusername_idChanging(int value);
    partial void Onusername_idChanged();
    partial void Onusername_usernameChanging(string value);
    partial void Onusername_usernameChanged();
    partial void Onusername_passwordChanging(string value);
    partial void Onusername_passwordChanged();
    partial void Onusername_fullnameChanging(string value);
    partial void Onusername_fullnameChanged();
    partial void Onusername_genderChanging(System.Nullable<bool> value);
    partial void Onusername_genderChanged();
    partial void Onusername_phoneChanging(string value);
    partial void Onusername_phoneChanged();
    partial void Onusername_emailChanging(string value);
    partial void Onusername_emailChanged();
    partial void Onusername_activeChanging(System.Nullable<bool> value);
    partial void Onusername_activeChanged();
    partial void Ongroupuser_idChanging(System.Nullable<int> value);
    partial void Ongroupuser_idChanged();
    #endregion
	
	public admin_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int username_id
	{
		get
		{
			return this._username_id;
		}
		set
		{
			if ((this._username_id != value))
			{
				this.Onusername_idChanging(value);
				this.SendPropertyChanging();
				this._username_id = value;
				this.SendPropertyChanged("username_id");
				this.Onusername_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_username", DbType="NVarChar(MAX)")]
	public string username_username
	{
		get
		{
			return this._username_username;
		}
		set
		{
			if ((this._username_username != value))
			{
				this.Onusername_usernameChanging(value);
				this.SendPropertyChanging();
				this._username_username = value;
				this.SendPropertyChanged("username_username");
				this.Onusername_usernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_password", DbType="NVarChar(MAX)")]
	public string username_password
	{
		get
		{
			return this._username_password;
		}
		set
		{
			if ((this._username_password != value))
			{
				this.Onusername_passwordChanging(value);
				this.SendPropertyChanging();
				this._username_password = value;
				this.SendPropertyChanged("username_password");
				this.Onusername_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_fullname", DbType="NVarChar(MAX)")]
	public string username_fullname
	{
		get
		{
			return this._username_fullname;
		}
		set
		{
			if ((this._username_fullname != value))
			{
				this.Onusername_fullnameChanging(value);
				this.SendPropertyChanging();
				this._username_fullname = value;
				this.SendPropertyChanged("username_fullname");
				this.Onusername_fullnameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_gender", DbType="Bit")]
	public System.Nullable<bool> username_gender
	{
		get
		{
			return this._username_gender;
		}
		set
		{
			if ((this._username_gender != value))
			{
				this.Onusername_genderChanging(value);
				this.SendPropertyChanging();
				this._username_gender = value;
				this.SendPropertyChanged("username_gender");
				this.Onusername_genderChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_phone", DbType="NVarChar(MAX)")]
	public string username_phone
	{
		get
		{
			return this._username_phone;
		}
		set
		{
			if ((this._username_phone != value))
			{
				this.Onusername_phoneChanging(value);
				this.SendPropertyChanging();
				this._username_phone = value;
				this.SendPropertyChanged("username_phone");
				this.Onusername_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_email", DbType="NVarChar(MAX)")]
	public string username_email
	{
		get
		{
			return this._username_email;
		}
		set
		{
			if ((this._username_email != value))
			{
				this.Onusername_emailChanging(value);
				this.SendPropertyChanging();
				this._username_email = value;
				this.SendPropertyChanged("username_email");
				this.Onusername_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_active", DbType="Bit")]
	public System.Nullable<bool> username_active
	{
		get
		{
			return this._username_active;
		}
		set
		{
			if ((this._username_active != value))
			{
				this.Onusername_activeChanging(value);
				this.SendPropertyChanging();
				this._username_active = value;
				this.SendPropertyChanged("username_active");
				this.Onusername_activeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_groupuser_id", DbType="Int")]
	public System.Nullable<int> groupuser_id
	{
		get
		{
			return this._groupuser_id;
		}
		set
		{
			if ((this._groupuser_id != value))
			{
				this.Ongroupuser_idChanging(value);
				this.SendPropertyChanging();
				this._groupuser_id = value;
				this.SendPropertyChanged("groupuser_id");
				this.Ongroupuser_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Category")]
public partial class tb_Category : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _cate_id;
	
	private string _cate_name;
	
	private string @__keywords;
	
	private string @__description;
	
	private string _link;
	
	private System.Nullable<bool> _cate_acti;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncate_idChanging(int value);
    partial void Oncate_idChanged();
    partial void Oncate_nameChanging(string value);
    partial void Oncate_nameChanged();
    partial void On_keywordsChanging(string value);
    partial void On_keywordsChanged();
    partial void On_descriptionChanging(string value);
    partial void On_descriptionChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void Oncate_actiChanging(System.Nullable<bool> value);
    partial void Oncate_actiChanged();
    #endregion
	
	public tb_Category()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int cate_id
	{
		get
		{
			return this._cate_id;
		}
		set
		{
			if ((this._cate_id != value))
			{
				this.Oncate_idChanging(value);
				this.SendPropertyChanging();
				this._cate_id = value;
				this.SendPropertyChanged("cate_id");
				this.Oncate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_name", DbType="NVarChar(MAX)")]
	public string cate_name
	{
		get
		{
			return this._cate_name;
		}
		set
		{
			if ((this._cate_name != value))
			{
				this.Oncate_nameChanging(value);
				this.SendPropertyChanging();
				this._cate_name = value;
				this.SendPropertyChanged("cate_name");
				this.Oncate_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_keywords]", Storage="__keywords", DbType="NVarChar(MAX)")]
	public string _keywords
	{
		get
		{
			return this.@__keywords;
		}
		set
		{
			if ((this.@__keywords != value))
			{
				this.On_keywordsChanging(value);
				this.SendPropertyChanging();
				this.@__keywords = value;
				this.SendPropertyChanged("_keywords");
				this.On_keywordsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_description]", Storage="__description", DbType="NVarChar(MAX)")]
	public string _description
	{
		get
		{
			return this.@__description;
		}
		set
		{
			if ((this.@__description != value))
			{
				this.On_descriptionChanging(value);
				this.SendPropertyChanging();
				this.@__description = value;
				this.SendPropertyChanged("_description");
				this.On_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(MAX)")]
	public string link
	{
		get
		{
			return this._link;
		}
		set
		{
			if ((this._link != value))
			{
				this.OnlinkChanging(value);
				this.SendPropertyChanging();
				this._link = value;
				this.SendPropertyChanged("link");
				this.OnlinkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_acti", DbType="Bit")]
	public System.Nullable<bool> cate_acti
	{
		get
		{
			return this._cate_acti;
		}
		set
		{
			if ((this._cate_acti != value))
			{
				this.Oncate_actiChanging(value);
				this.SendPropertyChanging();
				this._cate_acti = value;
				this.SendPropertyChanged("cate_acti");
				this.Oncate_actiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Product")]
public partial class tb_Product : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _pr_id;
	
	private string _pr_name;
	
	private string _pr_content;
	
	private string _pr_price;
	
	private string _pr_information;
	
	private string _pr_image;
	
	private string _pr_status;
	
	private string @__keywords;
	
	private string @__description;
	
	private System.Nullable<int> _cate_id;
	
	private string _link;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpr_idChanging(int value);
    partial void Onpr_idChanged();
    partial void Onpr_nameChanging(string value);
    partial void Onpr_nameChanged();
    partial void Onpr_contentChanging(string value);
    partial void Onpr_contentChanged();
    partial void Onpr_priceChanging(string value);
    partial void Onpr_priceChanged();
    partial void Onpr_informationChanging(string value);
    partial void Onpr_informationChanged();
    partial void Onpr_imageChanging(string value);
    partial void Onpr_imageChanged();
    partial void Onpr_statusChanging(string value);
    partial void Onpr_statusChanged();
    partial void On_keywordsChanging(string value);
    partial void On_keywordsChanged();
    partial void On_descriptionChanging(string value);
    partial void On_descriptionChanged();
    partial void Oncate_idChanging(System.Nullable<int> value);
    partial void Oncate_idChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    #endregion
	
	public tb_Product()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int pr_id
	{
		get
		{
			return this._pr_id;
		}
		set
		{
			if ((this._pr_id != value))
			{
				this.Onpr_idChanging(value);
				this.SendPropertyChanging();
				this._pr_id = value;
				this.SendPropertyChanged("pr_id");
				this.Onpr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_name", DbType="NVarChar(MAX)")]
	public string pr_name
	{
		get
		{
			return this._pr_name;
		}
		set
		{
			if ((this._pr_name != value))
			{
				this.Onpr_nameChanging(value);
				this.SendPropertyChanging();
				this._pr_name = value;
				this.SendPropertyChanged("pr_name");
				this.Onpr_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_content", DbType="NVarChar(MAX)")]
	public string pr_content
	{
		get
		{
			return this._pr_content;
		}
		set
		{
			if ((this._pr_content != value))
			{
				this.Onpr_contentChanging(value);
				this.SendPropertyChanging();
				this._pr_content = value;
				this.SendPropertyChanged("pr_content");
				this.Onpr_contentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_price", DbType="NVarChar(MAX)")]
	public string pr_price
	{
		get
		{
			return this._pr_price;
		}
		set
		{
			if ((this._pr_price != value))
			{
				this.Onpr_priceChanging(value);
				this.SendPropertyChanging();
				this._pr_price = value;
				this.SendPropertyChanged("pr_price");
				this.Onpr_priceChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_information", DbType="NVarChar(MAX)")]
	public string pr_information
	{
		get
		{
			return this._pr_information;
		}
		set
		{
			if ((this._pr_information != value))
			{
				this.Onpr_informationChanging(value);
				this.SendPropertyChanging();
				this._pr_information = value;
				this.SendPropertyChanged("pr_information");
				this.Onpr_informationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_image", DbType="NVarChar(MAX)")]
	public string pr_image
	{
		get
		{
			return this._pr_image;
		}
		set
		{
			if ((this._pr_image != value))
			{
				this.Onpr_imageChanging(value);
				this.SendPropertyChanging();
				this._pr_image = value;
				this.SendPropertyChanged("pr_image");
				this.Onpr_imageChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_status", DbType="NVarChar(MAX)")]
	public string pr_status
	{
		get
		{
			return this._pr_status;
		}
		set
		{
			if ((this._pr_status != value))
			{
				this.Onpr_statusChanging(value);
				this.SendPropertyChanging();
				this._pr_status = value;
				this.SendPropertyChanged("pr_status");
				this.Onpr_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_keywords]", Storage="__keywords", DbType="NVarChar(MAX)")]
	public string _keywords
	{
		get
		{
			return this.@__keywords;
		}
		set
		{
			if ((this.@__keywords != value))
			{
				this.On_keywordsChanging(value);
				this.SendPropertyChanging();
				this.@__keywords = value;
				this.SendPropertyChanged("_keywords");
				this.On_keywordsChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_description]", Storage="__description", DbType="NVarChar(MAX)")]
	public string _description
	{
		get
		{
			return this.@__description;
		}
		set
		{
			if ((this.@__description != value))
			{
				this.On_descriptionChanging(value);
				this.SendPropertyChanging();
				this.@__description = value;
				this.SendPropertyChanged("_description");
				this.On_descriptionChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cate_id", DbType="Int")]
	public System.Nullable<int> cate_id
	{
		get
		{
			return this._cate_id;
		}
		set
		{
			if ((this._cate_id != value))
			{
				this.Oncate_idChanging(value);
				this.SendPropertyChanging();
				this._cate_id = value;
				this.SendPropertyChanged("cate_id");
				this.Oncate_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="VarChar(MAX)")]
	public string link
	{
		get
		{
			return this._link;
		}
		set
		{
			if ((this._link != value))
			{
				this.OnlinkChanging(value);
				this.SendPropertyChanging();
				this._link = value;
				this.SendPropertyChanged("link");
				this.OnlinkChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_slide")]
public partial class tb_slide : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _slide_id;
	
	private string _slide_title;
	
	private string _slide_img;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onslide_idChanging(int value);
    partial void Onslide_idChanged();
    partial void Onslide_titleChanging(string value);
    partial void Onslide_titleChanged();
    partial void Onslide_imgChanging(string value);
    partial void Onslide_imgChanged();
    #endregion
	
	public tb_slide()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slide_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int slide_id
	{
		get
		{
			return this._slide_id;
		}
		set
		{
			if ((this._slide_id != value))
			{
				this.Onslide_idChanging(value);
				this.SendPropertyChanging();
				this._slide_id = value;
				this.SendPropertyChanged("slide_id");
				this.Onslide_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slide_title", DbType="NVarChar(MAX)")]
	public string slide_title
	{
		get
		{
			return this._slide_title;
		}
		set
		{
			if ((this._slide_title != value))
			{
				this.Onslide_titleChanging(value);
				this.SendPropertyChanging();
				this._slide_title = value;
				this.SendPropertyChanged("slide_title");
				this.Onslide_titleChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_slide_img", DbType="NVarChar(MAX)")]
	public string slide_img
	{
		get
		{
			return this._slide_img;
		}
		set
		{
			if ((this._slide_img != value))
			{
				this.Onslide_imgChanging(value);
				this.SendPropertyChanging();
				this._slide_img = value;
				this.SendPropertyChanged("slide_img");
				this.Onslide_imgChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_User")]
public partial class tb_User : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _us_id;
	
	private string _us_name;
	
	private string _us_phone;
	
	private string _us_address;
	
	private string _us_email;
	
	private string _us_username;
	
	private string _us_password;
	
	private System.Nullable<bool> _us_acti;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onus_idChanging(int value);
    partial void Onus_idChanged();
    partial void Onus_nameChanging(string value);
    partial void Onus_nameChanged();
    partial void Onus_phoneChanging(string value);
    partial void Onus_phoneChanged();
    partial void Onus_addressChanging(string value);
    partial void Onus_addressChanged();
    partial void Onus_emailChanging(string value);
    partial void Onus_emailChanged();
    partial void Onus_usernameChanging(string value);
    partial void Onus_usernameChanged();
    partial void Onus_passwordChanging(string value);
    partial void Onus_passwordChanged();
    partial void Onus_actiChanging(System.Nullable<bool> value);
    partial void Onus_actiChanged();
    #endregion
	
	public tb_User()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int us_id
	{
		get
		{
			return this._us_id;
		}
		set
		{
			if ((this._us_id != value))
			{
				this.Onus_idChanging(value);
				this.SendPropertyChanging();
				this._us_id = value;
				this.SendPropertyChanged("us_id");
				this.Onus_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_name", DbType="NVarChar(MAX)")]
	public string us_name
	{
		get
		{
			return this._us_name;
		}
		set
		{
			if ((this._us_name != value))
			{
				this.Onus_nameChanging(value);
				this.SendPropertyChanging();
				this._us_name = value;
				this.SendPropertyChanged("us_name");
				this.Onus_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_phone", DbType="NVarChar(MAX)")]
	public string us_phone
	{
		get
		{
			return this._us_phone;
		}
		set
		{
			if ((this._us_phone != value))
			{
				this.Onus_phoneChanging(value);
				this.SendPropertyChanging();
				this._us_phone = value;
				this.SendPropertyChanged("us_phone");
				this.Onus_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_address", DbType="NVarChar(MAX)")]
	public string us_address
	{
		get
		{
			return this._us_address;
		}
		set
		{
			if ((this._us_address != value))
			{
				this.Onus_addressChanging(value);
				this.SendPropertyChanging();
				this._us_address = value;
				this.SendPropertyChanged("us_address");
				this.Onus_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_email", DbType="NVarChar(MAX)")]
	public string us_email
	{
		get
		{
			return this._us_email;
		}
		set
		{
			if ((this._us_email != value))
			{
				this.Onus_emailChanging(value);
				this.SendPropertyChanging();
				this._us_email = value;
				this.SendPropertyChanged("us_email");
				this.Onus_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_username", DbType="NVarChar(MAX)")]
	public string us_username
	{
		get
		{
			return this._us_username;
		}
		set
		{
			if ((this._us_username != value))
			{
				this.Onus_usernameChanging(value);
				this.SendPropertyChanging();
				this._us_username = value;
				this.SendPropertyChanged("us_username");
				this.Onus_usernameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_password", DbType="NVarChar(MAX)")]
	public string us_password
	{
		get
		{
			return this._us_password;
		}
		set
		{
			if ((this._us_password != value))
			{
				this.Onus_passwordChanging(value);
				this.SendPropertyChanging();
				this._us_password = value;
				this.SendPropertyChanged("us_password");
				this.Onus_passwordChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_acti", DbType="Bit")]
	public System.Nullable<bool> us_acti
	{
		get
		{
			return this._us_acti;
		}
		set
		{
			if ((this._us_acti != value))
			{
				this.Onus_actiChanging(value);
				this.SendPropertyChanging();
				this._us_acti = value;
				this.SendPropertyChanged("us_acti");
				this.Onus_actiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Restaurant")]
public partial class tb_Restaurant : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _re_id;
	
	private string _re_name;
	
	private string _re_address;
	
	private string _link;
	
	private string _phone;
	
	private string _email;
	
	private string _acti;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onre_idChanging(int value);
    partial void Onre_idChanged();
    partial void Onre_nameChanging(string value);
    partial void Onre_nameChanged();
    partial void Onre_addressChanging(string value);
    partial void Onre_addressChanged();
    partial void OnlinkChanging(string value);
    partial void OnlinkChanged();
    partial void OnphoneChanging(string value);
    partial void OnphoneChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnactiChanging(string value);
    partial void OnactiChanged();
    #endregion
	
	public tb_Restaurant()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_re_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int re_id
	{
		get
		{
			return this._re_id;
		}
		set
		{
			if ((this._re_id != value))
			{
				this.Onre_idChanging(value);
				this.SendPropertyChanging();
				this._re_id = value;
				this.SendPropertyChanged("re_id");
				this.Onre_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_re_name", DbType="NVarChar(MAX)")]
	public string re_name
	{
		get
		{
			return this._re_name;
		}
		set
		{
			if ((this._re_name != value))
			{
				this.Onre_nameChanging(value);
				this.SendPropertyChanging();
				this._re_name = value;
				this.SendPropertyChanged("re_name");
				this.Onre_nameChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_re_address", DbType="NVarChar(MAX)")]
	public string re_address
	{
		get
		{
			return this._re_address;
		}
		set
		{
			if ((this._re_address != value))
			{
				this.Onre_addressChanging(value);
				this.SendPropertyChanging();
				this._re_address = value;
				this.SendPropertyChanged("re_address");
				this.Onre_addressChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_link", DbType="NVarChar(MAX)")]
	public string link
	{
		get
		{
			return this._link;
		}
		set
		{
			if ((this._link != value))
			{
				this.OnlinkChanging(value);
				this.SendPropertyChanging();
				this._link = value;
				this.SendPropertyChanged("link");
				this.OnlinkChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="VarChar(MAX)")]
	public string phone
	{
		get
		{
			return this._phone;
		}
		set
		{
			if ((this._phone != value))
			{
				this.OnphoneChanging(value);
				this.SendPropertyChanging();
				this._phone = value;
				this.SendPropertyChanged("phone");
				this.OnphoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(MAX)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_acti", DbType="VarChar(MAX)")]
	public string acti
	{
		get
		{
			return this._acti;
		}
		set
		{
			if ((this._acti != value))
			{
				this.OnactiChanging(value);
				this.SendPropertyChanging();
				this._acti = value;
				this.SendPropertyChanged("acti");
				this.OnactiChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Book")]
public partial class tb_Book : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _book_id;
	
	private string _book_orderer;
	
	private string _book_status;
	
	private System.Nullable<int> _book_number;
	
	private string _book_email;
	
	private string _book_phone;
	
	private string _book_note;
	
	private System.Nullable<System.DateTime> _book_date;
	
	private System.Nullable<System.TimeSpan> _book_time;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbook_idChanging(int value);
    partial void Onbook_idChanged();
    partial void Onbook_ordererChanging(string value);
    partial void Onbook_ordererChanged();
    partial void Onbook_statusChanging(string value);
    partial void Onbook_statusChanged();
    partial void Onbook_numberChanging(System.Nullable<int> value);
    partial void Onbook_numberChanged();
    partial void Onbook_emailChanging(string value);
    partial void Onbook_emailChanged();
    partial void Onbook_phoneChanging(string value);
    partial void Onbook_phoneChanged();
    partial void Onbook_noteChanging(string value);
    partial void Onbook_noteChanged();
    partial void Onbook_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onbook_dateChanged();
    partial void Onbook_timeChanging(System.Nullable<System.TimeSpan> value);
    partial void Onbook_timeChanged();
    #endregion
	
	public tb_Book()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int book_id
	{
		get
		{
			return this._book_id;
		}
		set
		{
			if ((this._book_id != value))
			{
				this.Onbook_idChanging(value);
				this.SendPropertyChanging();
				this._book_id = value;
				this.SendPropertyChanged("book_id");
				this.Onbook_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_orderer", DbType="NVarChar(MAX)")]
	public string book_orderer
	{
		get
		{
			return this._book_orderer;
		}
		set
		{
			if ((this._book_orderer != value))
			{
				this.Onbook_ordererChanging(value);
				this.SendPropertyChanging();
				this._book_orderer = value;
				this.SendPropertyChanged("book_orderer");
				this.Onbook_ordererChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_status", DbType="NVarChar(MAX)")]
	public string book_status
	{
		get
		{
			return this._book_status;
		}
		set
		{
			if ((this._book_status != value))
			{
				this.Onbook_statusChanging(value);
				this.SendPropertyChanging();
				this._book_status = value;
				this.SendPropertyChanged("book_status");
				this.Onbook_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_number", DbType="Int")]
	public System.Nullable<int> book_number
	{
		get
		{
			return this._book_number;
		}
		set
		{
			if ((this._book_number != value))
			{
				this.Onbook_numberChanging(value);
				this.SendPropertyChanging();
				this._book_number = value;
				this.SendPropertyChanged("book_number");
				this.Onbook_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_email", DbType="NVarChar(MAX)")]
	public string book_email
	{
		get
		{
			return this._book_email;
		}
		set
		{
			if ((this._book_email != value))
			{
				this.Onbook_emailChanging(value);
				this.SendPropertyChanging();
				this._book_email = value;
				this.SendPropertyChanged("book_email");
				this.Onbook_emailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_phone", DbType="NVarChar(MAX)")]
	public string book_phone
	{
		get
		{
			return this._book_phone;
		}
		set
		{
			if ((this._book_phone != value))
			{
				this.Onbook_phoneChanging(value);
				this.SendPropertyChanging();
				this._book_phone = value;
				this.SendPropertyChanged("book_phone");
				this.Onbook_phoneChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_note", DbType="NVarChar(MAX)")]
	public string book_note
	{
		get
		{
			return this._book_note;
		}
		set
		{
			if ((this._book_note != value))
			{
				this.Onbook_noteChanging(value);
				this.SendPropertyChanging();
				this._book_note = value;
				this.SendPropertyChanged("book_note");
				this.Onbook_noteChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_date", DbType="Date")]
	public System.Nullable<System.DateTime> book_date
	{
		get
		{
			return this._book_date;
		}
		set
		{
			if ((this._book_date != value))
			{
				this.Onbook_dateChanging(value);
				this.SendPropertyChanging();
				this._book_date = value;
				this.SendPropertyChanged("book_date");
				this.Onbook_dateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_book_time", DbType="Time")]
	public System.Nullable<System.TimeSpan> book_time
	{
		get
		{
			return this._book_time;
		}
		set
		{
			if ((this._book_time != value))
			{
				this.Onbook_timeChanging(value);
				this.SendPropertyChanging();
				this._book_time = value;
				this.SendPropertyChanged("book_time");
				this.Onbook_timeChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_OrderDetail")]
public partial class tb_OrderDetail : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _ord_id;
	
	private System.Nullable<int> _pr_id;
	
	private string _pr_pricecurrent;
	
	private System.Nullable<int> _pr_number;
	
	private System.Nullable<int> _order_id;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onord_idChanging(int value);
    partial void Onord_idChanged();
    partial void Onpr_idChanging(System.Nullable<int> value);
    partial void Onpr_idChanged();
    partial void Onpr_pricecurrentChanging(string value);
    partial void Onpr_pricecurrentChanged();
    partial void Onpr_numberChanging(System.Nullable<int> value);
    partial void Onpr_numberChanged();
    partial void Onorder_idChanging(System.Nullable<int> value);
    partial void Onorder_idChanged();
    #endregion
	
	public tb_OrderDetail()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ord_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int ord_id
	{
		get
		{
			return this._ord_id;
		}
		set
		{
			if ((this._ord_id != value))
			{
				this.Onord_idChanging(value);
				this.SendPropertyChanging();
				this._ord_id = value;
				this.SendPropertyChanged("ord_id");
				this.Onord_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_id", DbType="Int")]
	public System.Nullable<int> pr_id
	{
		get
		{
			return this._pr_id;
		}
		set
		{
			if ((this._pr_id != value))
			{
				this.Onpr_idChanging(value);
				this.SendPropertyChanging();
				this._pr_id = value;
				this.SendPropertyChanged("pr_id");
				this.Onpr_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_pricecurrent", DbType="NVarChar(MAX)")]
	public string pr_pricecurrent
	{
		get
		{
			return this._pr_pricecurrent;
		}
		set
		{
			if ((this._pr_pricecurrent != value))
			{
				this.Onpr_pricecurrentChanging(value);
				this.SendPropertyChanging();
				this._pr_pricecurrent = value;
				this.SendPropertyChanged("pr_pricecurrent");
				this.Onpr_pricecurrentChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pr_number", DbType="Int")]
	public System.Nullable<int> pr_number
	{
		get
		{
			return this._pr_number;
		}
		set
		{
			if ((this._pr_number != value))
			{
				this.Onpr_numberChanging(value);
				this.SendPropertyChanging();
				this._pr_number = value;
				this.SendPropertyChanged("pr_number");
				this.Onpr_numberChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int")]
	public System.Nullable<int> order_id
	{
		get
		{
			return this._order_id;
		}
		set
		{
			if ((this._order_id != value))
			{
				this.Onorder_idChanging(value);
				this.SendPropertyChanging();
				this._order_id = value;
				this.SendPropertyChanged("order_id");
				this.Onorder_idChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tb_Order")]
public partial class tb_Order : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _order_id;
	
	private System.Nullable<System.DateTime> _order_creationdate;
	
	private System.Nullable<int> _us_id;
	
	private string _order_status;
	
	private System.Nullable<int> _username_id;
	
	private string _order_total;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onorder_creationdateChanging(System.Nullable<System.DateTime> value);
    partial void Onorder_creationdateChanged();
    partial void Onus_idChanging(System.Nullable<int> value);
    partial void Onus_idChanged();
    partial void Onorder_statusChanging(string value);
    partial void Onorder_statusChanged();
    partial void Onusername_idChanging(System.Nullable<int> value);
    partial void Onusername_idChanged();
    partial void Onorder_totalChanging(string value);
    partial void Onorder_totalChanged();
    #endregion
	
	public tb_Order()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int order_id
	{
		get
		{
			return this._order_id;
		}
		set
		{
			if ((this._order_id != value))
			{
				this.Onorder_idChanging(value);
				this.SendPropertyChanging();
				this._order_id = value;
				this.SendPropertyChanged("order_id");
				this.Onorder_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_creationdate", DbType="DateTime")]
	public System.Nullable<System.DateTime> order_creationdate
	{
		get
		{
			return this._order_creationdate;
		}
		set
		{
			if ((this._order_creationdate != value))
			{
				this.Onorder_creationdateChanging(value);
				this.SendPropertyChanging();
				this._order_creationdate = value;
				this.SendPropertyChanged("order_creationdate");
				this.Onorder_creationdateChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_us_id", DbType="Int")]
	public System.Nullable<int> us_id
	{
		get
		{
			return this._us_id;
		}
		set
		{
			if ((this._us_id != value))
			{
				this.Onus_idChanging(value);
				this.SendPropertyChanging();
				this._us_id = value;
				this.SendPropertyChanged("us_id");
				this.Onus_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_status", DbType="NVarChar(MAX)")]
	public string order_status
	{
		get
		{
			return this._order_status;
		}
		set
		{
			if ((this._order_status != value))
			{
				this.Onorder_statusChanging(value);
				this.SendPropertyChanging();
				this._order_status = value;
				this.SendPropertyChanged("order_status");
				this.Onorder_statusChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username_id", DbType="Int")]
	public System.Nullable<int> username_id
	{
		get
		{
			return this._username_id;
		}
		set
		{
			if ((this._username_id != value))
			{
				this.Onusername_idChanging(value);
				this.SendPropertyChanging();
				this._username_id = value;
				this.SendPropertyChanged("username_id");
				this.Onusername_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_total", DbType="NVarChar(MAX)")]
	public string order_total
	{
		get
		{
			return this._order_total;
		}
		set
		{
			if ((this._order_total != value))
			{
				this.Onorder_totalChanging(value);
				this.SendPropertyChanging();
				this._order_total = value;
				this.SendPropertyChanged("order_total");
				this.Onorder_totalChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
